#Determines if an integrated webserver with a screenshot gallery should be started
screenshotWebserver: true
#Port of the Webserver
port: 4567
#IP address the webserver should bind to. Use 0.0.0.0 for all network interfaces, or 127.0.0.1 to restrict to localhost
host: "0.0.0.0"
#Allow EVERYONE with the passphrase to delete screenshots
allowDelete: false
#Passphrase for deleting screenshots from the web gallery, ONLY SHARE WITH TRUSTED PEOPLE, Leave empty to allow everyone to delete screenshots
deletionPassphrase: ""
#Allow OPs to delete screenshots ingame
allowOpsToDelete: true
#Allow Players to delete ALL screenshots ingame
allowPlayersToDelete: false
#Allow Players to delete their own screenshots ingame
allowPlayersToDeleteOwn: true
#The public URL of the webserver !(must be configured for proper functionality)
websiteURL: ""
#if the url with a list of all screenshots should be sent to the client(required for ingame server gallery to work)
sendGalleryUrlToClient: true
# If the server should send an uploadUrl to the clients
sendUrlToClient: true
#Replace the server's upload URL with a custom one sent to the player
useCustomWebURL: false
#The custom URL to send to players
customWebURL: ""
#If the server should send a Discord Message in a channel (Requires Thread Channel webhookUrl needs to be set to work)
sendDiscordWebhook: false
#The Url of the Discord webhook
webhookUrl: ""
#If the server should delete screenshots older than a certain amount of days
deleteOldScreenshots: false
#The amount of days after which the screenshots should be deleted
deleteAfterDays: 30
#If static files should be replaced on server start, Turn off if you want to use custom js / css, Note: You wont be able to use new features if you turn this off
replaceStaticFilesOnStart: true